/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package it.unisannio.rcost.callgraphanalyzer.validation;


/**
 * A sample validator interface for {@link it.unisannio.rcost.callgraphanalyzer.Advice}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AdviceValidator {
	boolean validate();

	boolean validateIsStrictFp(boolean value);

	boolean validateKind(String value);

	boolean validateLocalId(int value);

	boolean validateSignature(Short value);

	boolean validateSignature(String value);

	boolean validatePointcutExpression(String value);

	boolean validatePoincutExpression(String value);

}
