/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package it.unisannio.rcost.callgraphanalyzer.validation;

import it.unisannio.rcost.callgraphanalyzer.ScopeModifier;


/**
 * A sample validator interface for {@link it.unisannio.rcost.callgraphanalyzer.Field}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FieldValidator {
	boolean validate();

	boolean validateIsStrictFP(boolean value);

	boolean validateIsFinal(boolean value);

	boolean validateIsStatic(boolean value);

	boolean validateIsVolatile(boolean value);

	boolean validateSignature(String value);

	boolean validateScopeModifier(ScopeModifier value);

	boolean validateIsTransient(boolean value);

	boolean validateScopeModifier(String value);

}
