/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package it.unisannio.rcost.callgraphanalyzer.validation;

import it.unisannio.rcost.callgraphanalyzer.Edge;

import it.unisannio.rcost.callgraphanalyzer.NodeContainer;
import org.eclipse.emf.common.util.EList;
import org.eclipse.jdt.core.IMember;

/**
 * A sample validator interface for {@link it.unisannio.rcost.callgraphanalyzer.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateInEdges(EList<Edge> value);
	boolean validateOutEdges(EList<Edge> value);
	boolean validateName(String value);

	boolean validateNodeContainer(NodeContainer value);

	boolean validateIMember(IMember value);

	boolean validateId(int value);

	boolean validateIMember(Object value);
}
